# service is part of the core that`s why we specify only version
apiVersion: v1
kind: Service
metadata:
  name: ps-nodeport   # name of the service
spec:
  type: NodePort
  ports:
  - port: 80          # service port
    targetPort: 8080  # port from container on which the app is listening
    nodePort: 31111   # must be in range: 30000-32767
    protocol: TCP     # default is TCP (could be skipped in this case)
  selector:
    app: web          # this service will forward traffic to all pods that have label 'app: web'
    