{{ define "mychart.labels" }}
  labels:
    fullName: {{ .Values.personal.name }} {{ .Values.personal.secondName }}
    country: {{ .Values.personal.country -}}
{{ end }}
customer:
  {{- template "mychart.labels" . -}}
customer1:
  {{- template "mychart.labels" . }}