apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
spec:
  replicas: 3
  # selector is used to point which pods should be managed by this replication controller
  selector:
    app: nginx-app  
  template:
    metadata:
      # it looks that this name is not used as pod name because created pods have names nginx-rc-*
      name: nginx-pod
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx-container
        image: nginx
        ports:
        - containerPort: 80
