apiVersion: apps/v1
kind: Deployment                # 'Deployment' object will be created
metadata:
  name: web-deploy
  labels:
    app: web                    # this label causes the created `Deployment` object will manage `ReplicaSet` object which has label `app: web`
                                # and all all nodes that have label `app: web`
                                # it is needed because during update a new `ReplicaSet` object is created and old pods mut be deleted
spec:
  replicas: 5                   # how many pods this deployment should create ( created `ReplicaSet` object will be responsible for it)
  selector:
    matchLabels:
      app: web                  # this label specifies that created `ReplicaSet` should manage all pods that have label `app: web`
                                # additionally it causes also that created `ReplicaSet` will have label `app: web`
  template:
    metadata:
      labels:
        app: web                # this label will be assigned to all pods created by this deployment
    spec: 
      terminationGracePeriodSeconds: 1
      containers:
      - name: hello-pod
        image: kicaj29/another-app:1.0
        imagePullPolicy: Always # always pull images from the registry, any time a node runs a container it creates local copy of the image
                                # it is good for development scenario to speed up things but it opens you up to malicious code. 
                                # Anyone could have put an image locally on a node and given it this name that we're trying to use.
                                # Using imagePullPolicy as Always is more secure.
        ports:
        - containerPort: 8080   # containerPort has to match port set in dockerfile 'EXPOSE 8080'