apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    # Defines how the created ReplicaSet finds which Pods to manage.
    # Typically it is the same value as value defined in the template metadata.
    matchLabels:
      app: frontend 
  template:
    # Allows identify created pods.
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: phico/frontend:1.0
        imagePullPolicy: Always
        name: frontend
        ports:
        - name: frontend
          containerPort: 4200

