apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
    - name: my-container
      image: alpine
      # https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/
      # by default alpine container exists as soon as the "start" process finishes
      # to keep container running create a loop
      # https://stackoverflow.com/questions/39729241/why-does-the-container-created-with-docker-run-d-alpine-sleep-infinity-goes/39729598#39729598
      command: ["/bin/sh"]
      args: ["-c", "echo 'apiToken=$(API_TOKEN)' && while sleep 3600; do :; done"]
      env:
      - name: API_TOKEN
        valueFrom:
          secretKeyRef:
            name: my-secret
            key: API_TOKEN
      volumeMounts:
        - name: secret-volume
          mountPath: "/config"
          readOnly: true
  volumes:
    - name: secret-volume
      secret:
        secretName: my-cli-secret         