# Read more about ingress class: https://sam-thomas.medium.com/kubernetes-ingressclass-error-ingress-does-not-contain-a-valid-ingressclass-78aab72c15a6
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-my-nginx
spec:
  controller: k8s.io/ingress-nginx # use your controller name. 
  # https://github.com/kubernetes/ingress-nginx/blob/main/internal/k8s/main.go#L126
  # https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
  # controller.ingressClassResource.controllerValue, default value is "k8s.io/ingress-nginx"