# Simple deployment used to deploy and manage the app
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deploy
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 5
  minReadySeconds: 8
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0 # the maximum number of pods that can be unavailable during the update process. This can be an absolute number or percentage of the replicas count; the default is 25%.
      maxSurge: 1       # the maximum number of pods that can be created over the desired number of pods. Again this can be an absolute number or a percentage of the replicas count; the default is 25%
                        # in this case we can go to 5+1 = 6
  template:
    metadata:
      labels:
        app: web
    spec: 
      terminationGracePeriodSeconds: 1
      containers:
      - name: hello-pod
        image: kicaj29/another-app:2.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080