apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: metrics-api-mongo-pool-size
  namespace: default
  labels:
    deploymentName: metrics-api-mongo-pool-size
spec:
  scaleTargetRef:
    name: ms-scale-me
  pollingInterval: 5
  cooldownPeriod: 10
  minReplicaCount: 0
  maxReplicaCount: 5
  triggers:
    - type: metrics-api
      metadata:
        targetValue: "2"
        url: "http://ms-custom-metrics.default.svc.cluster.local:80/api/metrics/mongo-connections"
        valueLocation: 'currentWaitingSize'